// Change history for a managed vault — server-side and tamper-resistant.
//
// A trigger on every data table writes to twin_audit whenever a row is
// inserted, updated or deleted, recording WHO (the member's id + email from
// their JWT), WHAT (table, row id, a human label), the ACTION, and for an
// update the exact fields that changed. Because the log is written by a
// security-definer trigger and members have only a SELECT policy on
// twin_audit, a member can read the history but cannot forge or erase it —
// which is the whole point of "who changed this" in a shared vault.
//
// Applied once by an admin through the service_role key (schemaSync
// ensureAuditSchema), the same gated path as plugin schemas. Idempotent:
// safe to re-run, and it only attaches triggers to tables that exist, so it
// grows automatically as more plugin tables are added.

import { PLUGIN_SCHEMAS } from './pluginSchemas.ts';

// Every table whose changes are worth recording: core contacts + all plugin
// tables. twin_audit itself and plugin_sync/app_files are deliberately left
// out (bookkeeping, not user data).
const CORE = [
  'Person',
  'organization',
  'Person_organization',
  'Person_email',
  'person_social',
  'organization_social'
];

export function auditedTables(): string[] {
  const plugin = Object.values(PLUGIN_SCHEMAS).flatMap((s) => s.tables);
  return [...new Set([...CORE, ...plugin])];
}

/** The full, idempotent audit DDL for a managed vault. */
export function auditSql(): string {
  const list = auditedTables()
    .map((t) => `'${t}'`)
    .join(',');
  return `-- twin: change history (audit log). Idempotent.
create table if not exists twin_audit (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid,
  actor_email text,
  action text not null,
  table_name text not null,
  row_id text,
  label text,
  changes jsonb
);

alter table twin_audit enable row level security;
-- Members READ the history; direct writes are denied (no write policy). The
-- trigger below is security-definer, so it inserts regardless — the log can
-- be read but never forged or edited by a member.
drop policy if exists twin_audit_read on twin_audit;
create policy twin_audit_read on twin_audit for select to authenticated using (true);

create or replace function twin_audit_row()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  j_old jsonb;
  j_new jsonb;
  diff jsonb;
  act text;
  rid text;
  lbl text;
begin
  if (tg_op = 'DELETE') then
    j_old := to_jsonb(OLD); j_new := null; act := 'delete';
  elsif (tg_op = 'INSERT') then
    j_old := null; j_new := to_jsonb(NEW); act := 'insert';
  else
    j_old := to_jsonb(OLD); j_new := to_jsonb(NEW); act := 'update';
  end if;

  rid := coalesce(j_new ->> 'id', j_old ->> 'id');
  lbl := coalesce(
    j_new ->> 'name', j_new ->> 'full_name', j_new ->> 'title',
    j_old ->> 'name', j_old ->> 'full_name', j_old ->> 'title'
  );

  if act = 'update' then
    select jsonb_object_agg(n.key, jsonb_build_object('from', j_old -> n.key, 'to', n.value))
      into diff
      from jsonb_each(j_new) n
     where (j_old -> n.key) is distinct from n.value
       and n.key not in ('date_updated', 'date_created');
    -- A no-op update (only timestamps moved) is not history worth keeping.
    if diff is null or diff = '{}'::jsonb then
      return NEW;
    end if;
  end if;

  insert into twin_audit (actor_id, actor_email, action, table_name, row_id, label, changes)
  values (
    auth.uid(),
    coalesce(nullif(auth.jwt() ->> 'email', ''), auth.uid()::text),
    act, tg_table_name, rid, lbl, diff
  );
  return coalesce(NEW, OLD);
end
$fn$;

do $$
declare t text;
begin
  foreach t in array array[${list}]
  loop
    if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = t) then
      execute format('drop trigger if exists twin_audit_t on %I', t);
      execute format('create trigger twin_audit_t after insert or update or delete on %I for each row execute function twin_audit_row()', t);
    end if;
  end loop;
end $$;
`;
}
