// The SQL that turns a fresh Supabase project into a twin backend.
//
// An anon key cannot run DDL, so the app cannot provision the schema itself —
// instead the Supabase option in StorageChooser hands the person this script
// to paste into their project's SQL Editor (Dashboard → SQL Editor → Run).
// Idempotent on purpose: running it twice, or on a project that already has
// some of the tables, is safe — the same contract as scripts/*.sh for
// Directus.
//
// The RLS stance is stated in the UI and repeated here: policies allow the
// anon role everything, which makes the PROJECT KEYS the access control.
// That is the right shape for a single-person cloud vault (treat the anon
// key like a password: whoever has URL + key has the vault) and the wrong
// shape for a team — per-user Supabase Auth with ownership policies
// (docs/phase3-supabase-rls.md §3) is the follow-up that changes it.

export const SUPABASE_SETUP_SQL = `-- twin: core schema for a Supabase-backed vault.
-- Idempotent: safe to run more than once. Paste into SQL Editor and Run.

create table if not exists "Person" (
  id bigint generated by default as identity primary key,
  full_name text, first_name text, last_name text, nickname text,
  email text, phone text,
  status text default 'draft', scope text default 'work',
  person_picture text, user_created text,
  date_created timestamptz default now(), date_updated timestamptz default now()
);

create table if not exists organization (
  id bigint generated by default as identity primary key,
  name text, website text, logo text, image_focal text,
  status text default 'active', scope text default 'work',
  lifecycle_status text, size text, industry text, user_created text,
  date_created timestamptz default now(), date_updated timestamptz default now()
);

create table if not exists "Person_organization" (
  id bigint generated by default as identity primary key,
  person_id bigint references "Person"(id),
  organization_id bigint references organization(id),
  role text, start_date date, end_date date, is_current boolean default true
);

create table if not exists "Person_email" (
  id bigint generated by default as identity primary key,
  person_id bigint references "Person"(id),
  email text not null,
  label text, source text, status text,
  date_created timestamptz default now()
);

create table if not exists person_social (
  id bigint generated by default as identity primary key,
  person_id bigint references "Person"(id),
  platform text, url text, handle text, sort integer
);

create table if not exists organization_social (
  id bigint generated by default as identity primary key,
  organization_id bigint references organization(id),
  platform text, url text, handle text, sort integer
);

create table if not exists plugin_sync (
  id bigint generated by default as identity primary key,
  disabled_plugins jsonb, enabled_plugins jsonb, plugin_settings jsonb
);

create table if not exists app_files (
  id bigint generated by default as identity primary key,
  title text, filename_download text, type text, url text, imported boolean,
  date_created timestamptz default now()
);

-- Access model: the project keys ARE the lock. The anon role may do
-- everything, so anyone holding your project URL + anon key holds the vault —
-- treat the key like a password and never publish it. Per-user auth with
-- ownership policies is the team-grade upgrade (see twin's docs).
do $$
declare t text;
begin
  foreach t in array array[
    'Person','organization','Person_organization','Person_email',
    'person_social','organization_social','plugin_sync','app_files'
  ]
  loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists twin_anon_all on %I', t);
    execute format('create policy twin_anon_all on %I for all to anon using (true) with check (true)', t);
  end loop;
end $$;
`;
